"""
abc_2_bronze — dlt ingestion pipeline for Notion → DuckDB.

Generated by vibedata-data-engineering for a verified dlt source.
Loads all accessible Notion databases from the abc_2 connection.

Configuration & secrets contract
--------------------------------
- Connection metadata is declared in `.dlt/config.toml` under
  `[studio.sources.abc_2]` (the studio overlay) plus the
  matching `[sources.abc_2.notion]` block that
  carries connector-native config.
- Credentials live in `.dlt/secrets.toml` under
  `[sources.abc_2.notion.credentials]` and resolve
  through dlt's stock provider chain (env override → secrets.toml → KV provider).
- For custom field reads, use:
      dlt.secrets["sources.abc_2.<field>"]
- Never read credentials from process environment or filesystem
  directly; rely on dlt's provider chain for resolution.

Pipeline behavior
-----------------
- notion_databases auto-discovers all accessible databases
- Each database becomes a separate table named by its title
- Write disposition: replace (full refresh on each run)
- Primary key: id
"""

import dlt
from notion import notion_databases


def run():
    """
    Load all accessible Notion databases from the abc_2 connection.

    The notion_databases source auto-discovers databases and yields
    one resource per database. Table names are derived from database titles.
    """
    pipeline = dlt.pipeline(
        pipeline_name="abc_2_bronze",
        destination=dlt.destinations.duckdb(credentials="./data/prod.duckdb"),
        dataset_name="src_abc_2",
    )

    # notion_databases is a source that auto-discovers all accessible databases
    # Pass section= to use the abc_2 connection config
    data = notion_databases.with_args(section="abc_2")()

    # Pin schema contract after successful initial load
    # Freezes columns, data_type, and tables to prevent schema drift
    for resource_name in data.resources.keys():
        data.resources[resource_name].apply_hints(
            schema_contract={
                "columns": "freeze",
                "data_type": "freeze",
                "tables": "freeze",
            }
        )

    # Run the pipeline
    load_info = pipeline.run(data)
    print(load_info)

    return load_info


if __name__ == "__main__":
    run()
